---
title: "Results"
author: "Hamza"
date: "10/02/2020"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#knitr::opts_knit$set(root.dir = '/Users/dominicmason/OneDrive\ -\ UNSW/hons') #sets WD as project for all chunks - doesn't change directory for setup chunk
#install.packages("pacman")
#install.packages("ggThemeAssist")
#install.packages("ggbeeswarm")
#install.packages("rptR")
#install.packages("lme4")
#install.packages("lmerTest")
#install.packages("wesanderson")
library(lmerTest)
library(ggThemeAssist)
library(rptR)
library(lme4)
library(emmeans)

pacman::p_load(readxl, tidyr, dplyr, magrittr, lubridate, stringr, purrr)

library(ggplot2)
library(lubridate)
library(wesanderson)
library(ggbeeswarm)
library(sjPlot)

p2cs <- read.csv("Joined.csv")
```

```{r}
source("./scripts/functions.R")
```


### Exploratory Analysis
```{r}
p2cs %>% 
  ggplot(aes(x = set, y = difference, colour = set)) +
  geom_violin(alpha = 0.1, draw_quantiles = c(0.25, 0.5, 0.75)) + 
  geom_jitter(width = 0.2, height = 0, alpha = 0.2) +
  theme_minimal()+
  facet_grid(~sex)
```
### Mixed model (2 min probe )
```{r}

model <- lmer(difference ~ set + sex + (1 | Fish_ID), data = p2cs)
qqnorm(residuals(model))
plot(model)
summary(model)
tab_model(model)
```