---
title: "Optimism"
author: "Hamza"
date: "20/02/2020"
output: html_document
---

### Load packages

```{r setup, include=FALSE}
#install.packages("pacman")
#install.packages("ggThemeAssist")
#install.packages("ggbeeswarm")
#install.packages("rptR")
#install.packages("lme4")
#install.packages("lmerTest")
#install.packages("wesanderson")
library(lmerTest)
library(ggThemeAssist)
library(rptR)
library(lme4)
library(readxl)
library(dplyr)
pacman::p_load(readxl, tidyr, dplyr, magrittr, lubridate, stringr, purrr)
library(sjPlot)
library(ggplot2)
library(lubridate)
library(wesanderson)
library(ggbeeswarm)
library(emmeans)
#sessionInfo()
#Install miktex and then run this to knit a pdf file
#install.packages('tinytex')
#tinytex::install_tinytex()
```

### Import and format data

```{r, include=FALSE}
Optimism <- read.csv("Optimism_Data.csv")
Optimism$Video_ID <- as.factor(Optimism$Video_ID)
Optimism$Time < as.factor(Optimism$Time)

#Function for filtering if needed
filter_etho <- function(Optimism, x, y){

  
Optimism %>% 
    filter(Video_ID %in% c(x)) %>%
    filter(Time == y)
}

#Join Phases to Data Frame
Video_ID <- read.csv("Video_ID.csv")
Video_ID$Video_ID <- as.factor(Video_ID$Video_ID)

left_join(Optimism, Video_ID, by = "Video_ID") -> Optimism


```

## Filtering positive data

```{r}
filter_etho(Optimism, c("1.2", "1.4", "2.2","2.4","3.2","3.4","4.2","4.4"), ("3-6")) -> Positive_Phase_1

filter_etho(Optimism, c("1.1","1.3","2.1","2.3","3.1","3.3","4.1","4.3"), ("9-12")) -> Positive_Phase_2

Positive_ALL <- bind_rows(Positive_Phase_1,Positive_Phase_2)
```

## Filtering negative data

```{r}
filter_etho(Optimism, c("1.2", "1.4", "2.2","2.4","3.2","3.4","4.2","4.4"), ("9-12")) -> Negative_Phase_2

filter_etho(Optimism, c("1.1","1.3","2.1","2.3","3.1","3.3","4.1","4.3"), ("3-6")) -> Negative_Phase_1

Negative_ALL <- bind_rows(Negative_Phase_1,Negative_Phase_2)
```

## Filtering mixed stim data

```{r}
Mixed_ALL <- Optimism %>% filter(Time == "15-18")
```

# Positive Analysis

```{r}
#Zone_05_dur


Positive_ALL %>% 
  ggplot(aes(x = Group, y = zone_05_dur, colour = Group)) +
  geom_violin(alpha = 0.1, draw_quantiles = c(0.25, 0.5, 0.75)) + 
  geom_jitter(width = 0.2, height = 0, alpha = 0.2) +
  theme_minimal()+
  labs(title = "Positive")+
  facet_grid(~Sex)



model_positive_05_dur <- lmer(zone_05_dur ~ Group*Sex  + (1 | Fish_ID), data = Positive_ALL)
tab_model(model_positive_05_dur)
hist(resid(model_positive_05_dur))
```

# Negative analysis


```{r}
#Zone_05_dur


Negative_ALL %>% 
  ggplot(aes(x = Group, y = zone_05_dur, colour = Group)) +
  geom_violin(alpha = 0.1, draw_quantiles = c(0.25, 0.5, 0.75)) + 
  geom_jitter(width = 0.2, height = 0, alpha = 0.2) +
  theme_minimal()+
  labs(title = "Negative Data")+
  facet_grid(~Sex)


model_negative_05_dur <- lmer(sqrt(zone_05_dur) ~ Group*Sex  + (1 | Fish_ID), data = Negative_ALL)
tab_model(model_negative_05_dur)
hist(resid(model_negative_05_dur))
```


# Mixed analysis
```{r}
#Zone_05_dur


Mixed_ALL %>% 
  ggplot(aes(x = Group, y = zone_05_dur, colour = Group)) +
  geom_violin(alpha = 0.1, draw_quantiles = c(0.25, 0.5, 0.75)) + 
  geom_jitter(width = 0.2, height = 0, alpha = 0.2) +
  theme_minimal()+
  labs(title = "Mixed Data")+
  facet_grid(~Sex)

model_mixed_05_dur <- lmer(zone_05_dur ~ Group*Sex  + (1 | Fish_ID), data = Mixed_ALL)
tab_model(model_mixed_05_dur)
hist(resid(model_mixed_05_dur))
```

# NEXT STEP...Filtering by the type of stimulus (and seeing their ICC) and looking at different variables 
















